Repository Leo-Corporation/Gerayis, pull requests merged in 2022-01, with the labels that each got.

#98 Update license copyright year(s)
  LICENSE
Labels: documentation

#100 Add Simplified Chinese language
  Gerayis/Properties/Resources.zh-CN.resx
Labels: vNext, roadmap, translation

#103 Version 1.9.1.2201
  Gerayis.Setup/Setup.iss
  Gerayis/Classes/Global.cs
  Gerayis/Gerayis.csproj
  Gerayis/MainWindow.xaml
  Gerayis/MainWindow.xaml.cs
  Gerayis/Pages/SettingsPage.xaml.cs
  Gerayis/Properties/Resources.Designer.cs
  Gerayis/Properties/Resources.en-US.resx
  Gerayis/Properties/Resources.fr-FR.resx
  Gerayis/Properties/Resources.resx
  Gerayis/Properties/Resources.zh-CN.resx
Labels: enhancement, vNext, roadmap
